package edu.upm.spbw.persistence.bo;

// Generated 01-mar-2016 14:25:13 by Hibernate Tools 3.4.0.CR1

/**
 * CspserpfId generated by hbm2java
 */
public class CspserpfId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String pfucpfuak;
	private String ssicssiak;

	public CspserpfId() {
	}

	public CspserpfId(String pfucpfuak, String ssicssiak) {
		this.pfucpfuak = pfucpfuak;
		this.ssicssiak = ssicssiak;
	}

	public String getPfucpfuak() {
		return this.pfucpfuak;
	}

	public void setPfucpfuak(String pfucpfuak) {
		this.pfucpfuak = pfucpfuak;
	}

	public String getSsicssiak() {
		return this.ssicssiak;
	}

	public void setSsicssiak(String ssicssiak) {
		this.ssicssiak = ssicssiak;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CspserpfId))
			return false;
		CspserpfId castOther = (CspserpfId) other;

		return ((this.getPfucpfuak() == castOther.getPfucpfuak()) || (this
				.getPfucpfuak() != null && castOther.getPfucpfuak() != null && this
				.getPfucpfuak().equals(castOther.getPfucpfuak())))
				&& ((this.getSsicssiak() == castOther.getSsicssiak()) || (this
						.getSsicssiak() != null
						&& castOther.getSsicssiak() != null && this
						.getSsicssiak().equals(castOther.getSsicssiak())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPfucpfuak() == null ? 0 : this.getPfucpfuak().hashCode());
		result = 37 * result
				+ (getSsicssiak() == null ? 0 : this.getSsicssiak().hashCode());
		return result;
	}

}
