package edu.upm.spbw.persistence.bo;

import edu.upm.spbw.utils.Constants;

// Generated 01-mar-2016 14:25:13 by Hibernate Tools 3.4.0.CR1

/**
 * Cspsersi generated by hbm2java
 */
public class Cspsersi implements java.io.Serializable, AbstractBO<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String ssicssiak;
	private String ssinssiaf;
	private String ssidssiaf;
	private String ssidurlaf;
	private String ssiiconaf;
	private String ssiiprosf;
	private String ssiidessf;
	private String ssiiactsf;
	/* booleanos */
	private boolean bssiiprosf;
	private boolean bssiidessf;
	private boolean bssiiactsf;

	public Cspsersi() {
	}

	public Cspsersi(String ssicssiak, String ssinssiaf, String ssidssiaf,
			String ssidurlaf, String ssiiconaf, String ssiiprosf,
			String ssiidessf, String ssiiactsf) {
		this.ssicssiak = ssicssiak;
		this.ssinssiaf = ssinssiaf;
		this.ssidssiaf = ssidssiaf;
		this.ssidurlaf = ssidurlaf;
		this.ssiiconaf = ssiiconaf;
		this.ssiiprosf = ssiiprosf;
		this.ssiidessf = ssiidessf;
		this.ssiiactsf = ssiiactsf;
	}

	public String getSsicssiak() {
		return this.ssicssiak;
	}

	public void setSsicssiak(String ssicssiak) {
		this.ssicssiak = ssicssiak;
	}

	public String getSsinssiaf() {
		return this.ssinssiaf;
	}

	public void setSsinssiaf(String ssinssiaf) {
		this.ssinssiaf = ssinssiaf;
	}

	public String getSsidssiaf() {
		return this.ssidssiaf;
	}

	public void setSsidssiaf(String ssidssiaf) {
		this.ssidssiaf = ssidssiaf;
	}

	/**
	 * @return the ssidurlaf
	 */
	public String getSsidurlaf() {
		return ssidurlaf;
	}

	/**
	 * @param ssidurlaf
	 *            the ssidurlaf to set
	 */
	public void setSsidurlaf(String ssidurlaf) {
		this.ssidurlaf = ssidurlaf;
	}

	public String getSsiiconaf() {
		return this.ssiiconaf;
	}

	public void setSsiiconaf(String ssiiconaf) {
		this.ssiiconaf = ssiiconaf;
	}

	public String getSsiiprosf() {
		return this.ssiiprosf;
	}

	public void setSsiiprosf(String ssiiprosf) {
		this.ssiiprosf = ssiiprosf;
	}

	/**
	 * @return the ssiidessf
	 */
	public String getSsiidessf() {
		return ssiidessf;
	}

	/**
	 * @param ssiidessf
	 *            the ssiidessf to set
	 */
	public void setSsiidessf(String ssiidessf) {
		this.ssiidessf = ssiidessf;
	}

	public String getSsiiactsf() {
		return this.ssiiactsf;
	}

	public void setSsiiactsf(String ssiiactsf) {
		this.ssiiactsf = ssiiactsf;
	}

	@Override
	public String getPrimaryKey() {
		return ssicssiak;
	}

	@Override
	public void prepareObject() {
		// Codigo servicio
		if (this.ssicssiak == null)
			this.ssicssiak = Constants.BLANKS;
		else
			this.ssicssiak = this.ssicssiak.trim();
		// Nombre servicio
		if (this.ssinssiaf == null)
			this.ssinssiaf = Constants.BLANKS;
		else
			this.ssinssiaf = this.ssinssiaf.trim();
		// Descripcion servicio
		if (this.ssidssiaf == null)
			this.ssidssiaf = Constants.BLANKS;
		else
			this.ssidssiaf = this.ssidssiaf.trim();

		// URL servicio
		if (this.ssidurlaf == null)
			this.ssidurlaf = Constants.BLANKS;
		else
			this.ssidurlaf = this.ssidurlaf.trim();
		// Icono servicio
		if (this.ssiiconaf == null)
			this.ssiiconaf = Constants.BLANKS;
		else
			this.ssiiconaf = this.ssiiconaf.trim();
		// Propio
		if (this.ssiiprosf == null)
			this.ssiiprosf = Constants.ZERO;
		else
			this.ssiiprosf = this.ssiiprosf.trim();
		// Desplegable
		if (this.ssiidessf == null)
			this.ssiidessf = Constants.ZERO;
		else
			this.ssiidessf = this.ssiidessf.trim();
		// Activo
		if (this.ssiiactsf == null)
			this.ssiiactsf = Constants.ZERO;
		else
			this.ssiiactsf = this.ssiiactsf.trim();
		// Booleanos
		this.bssiiprosf = Constants.ONE.equals(this.ssiiprosf);
		this.bssiidessf = Constants.ONE.equals(this.ssiidessf);
		this.bssiiactsf = Constants.ONE.equals(this.ssiiactsf);
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((ssicssiak == null) ? 0 : ssicssiak.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Cspsersi)) {
			return false;
		}
		Cspsersi other = (Cspsersi) obj;
		if (ssicssiak == null) {
			if (other.ssicssiak != null) {
				return false;
			}
		} else if (!ssicssiak.equals(other.ssicssiak)) {
			return false;
		}
		return true;
	}

	/**
	 * @return the bssiiprosf
	 */
	public boolean getBssiiprosf() {
		return bssiiprosf;
	}

	/**
	 * @param bssiiprosf
	 *            the bssiiprosf to set
	 */
	public void setBssiiprosf(boolean bssiiprosf) {
		this.bssiiprosf = bssiiprosf;
	}

	/**
	 * @return the bssiidessf
	 */
	public boolean getBssiidessf() {
		return bssiidessf;
	}

	/**
	 * @param bssiidessf
	 *            the bssiidessf to set
	 */
	public void setBssiidessf(boolean bssiidessf) {
		this.bssiidessf = bssiidessf;
	}

	/**
	 * @return the bssiiactsf
	 */
	public boolean getBssiiactsf() {
		return bssiiactsf;
	}

	/**
	 * @param bssiiactsf
	 *            the bssiiactsf to set
	 */
	public void setBssiiactsf(boolean bssiiactsf) {
		this.bssiiactsf = bssiiactsf;
	}

	@Override
	public void prepareToUpdate() {
		// Valores booleanos
		this.ssiiprosf = this.bssiiprosf ? Constants.ONE : Constants.ZERO;
		this.ssiidessf = this.bssiidessf ? Constants.ONE : Constants.ZERO;
		this.ssiiactsf = this.bssiiactsf ? Constants.ONE : Constants.ZERO;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Cspsersi ["
				+ (ssicssiak != null ? "ssicssiak=" + ssicssiak + ", " : "")
				+ (ssinssiaf != null ? "ssinssiaf=" + ssinssiaf + ", " : "")
				+ (ssidssiaf != null ? "ssidssiaf=" + ssidssiaf + ", " : "")
				+ (ssidurlaf != null ? "ssidurlaf=" + ssidurlaf + ", " : "")
				+ (ssiiconaf != null ? "ssiiconaf=" + ssiiconaf + ", " : "")
				+ (ssiiprosf != null ? "ssiiprosf=" + ssiiprosf + ", " : "")
				+ (ssiidessf != null ? "ssiidessf=" + ssiidessf + ", " : "")
				+ (ssiiactsf != null ? "ssiiactsf=" + ssiiactsf + ", " : "")
				+ "bssiiprosf=" + bssiiprosf + ", bssiidessf=" + bssiidessf
				+ ", bssiiactsf=" + bssiiactsf + "]";
	}

}
