package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:40:56 by Hibernate Tools 3.4.0.CR1

/**
 * SedrelcoId generated by hbm2java
 */
public class SedrelcoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dconsecnk;
	private int drcnsecnk;

	public SedrelcoId() {
	}

	public SedrelcoId(int dconsecnk, int drcnsecnk) {
		this.dconsecnk = dconsecnk;
		this.drcnsecnk = drcnsecnk;
	}

	public int getDconsecnk() {
		return this.dconsecnk;
	}

	public void setDconsecnk(int dconsecnk) {
		this.dconsecnk = dconsecnk;
	}

	public int getDrcnsecnk() {
		return this.drcnsecnk;
	}

	public void setDrcnsecnk(int drcnsecnk) {
		this.drcnsecnk = drcnsecnk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SedrelcoId))
			return false;
		SedrelcoId castOther = (SedrelcoId) other;

		return (this.getDconsecnk() == castOther.getDconsecnk())
				&& (this.getDrcnsecnk() == castOther.getDrcnsecnk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDconsecnk();
		result = 37 * result + this.getDrcnsecnk();
		return result;
	}

}
