package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:40:56 by Hibernate Tools 3.4.0.CR1

/**
 * SeprelcoId generated by hbm2java
 */
public class SeprelcoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cosccosak;
	private String rcocrcoak;

	public SeprelcoId() {
	}

	public SeprelcoId(String cosccosak, String rcocrcoak) {
		this.cosccosak = cosccosak;
		this.rcocrcoak = rcocrcoak;
	}

	public String getCosccosak() {
		return this.cosccosak;
	}

	public void setCosccosak(String cosccosak) {
		this.cosccosak = cosccosak;
	}

	public String getRcocrcoak() {
		return this.rcocrcoak;
	}

	public void setRcocrcoak(String rcocrcoak) {
		this.rcocrcoak = rcocrcoak;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeprelcoId))
			return false;
		SeprelcoId castOther = (SeprelcoId) other;

		return ((this.getCosccosak() == castOther.getCosccosak()) || (this
				.getCosccosak() != null && castOther.getCosccosak() != null && this
				.getCosccosak().equals(castOther.getCosccosak())))
				&& ((this.getRcocrcoak() == castOther.getRcocrcoak()) || (this
						.getRcocrcoak() != null
						&& castOther.getRcocrcoak() != null && this
						.getRcocrcoak().equals(castOther.getRcocrcoak())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCosccosak() == null ? 0 : this.getCosccosak().hashCode());
		result = 37 * result
				+ (getRcocrcoak() == null ? 0 : this.getRcocrcoak().hashCode());
		return result;
	}

}
