package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:50:28 by Hibernate Tools 3.4.0.CR1

/**
 * UsdbloquId generated by hbm2java
 */
public class UsdbloquId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String usuemaiak;
	private long usutblonf;

	public UsdbloquId() {
	}

	public UsdbloquId(String usuemaiak, long usutblonf) {
		this.usuemaiak = usuemaiak;
		this.usutblonf = usutblonf;
	}

	public String getUsuemaiak() {
		return this.usuemaiak;
	}

	public void setUsuemaiak(String usuemaiak) {
		this.usuemaiak = usuemaiak;
	}

	public long getUsutblonf() {
		return this.usutblonf;
	}

	public void setUsutblonf(long usutblonf) {
		this.usutblonf = usutblonf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsdbloquId))
			return false;
		UsdbloquId castOther = (UsdbloquId) other;

		return ((this.getUsuemaiak() == castOther.getUsuemaiak()) || (this
				.getUsuemaiak() != null && castOther.getUsuemaiak() != null && this
				.getUsuemaiak().equals(castOther.getUsuemaiak())))
				&& (this.getUsutblonf() == castOther.getUsutblonf());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsuemaiak() == null ? 0 : this.getUsuemaiak().hashCode());
		result = 37 * result + (int) this.getUsutblonf();
		return result;
	}

}
