package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:40:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Usdlogqu generated by hbm2java
 */
public class Usdlogqu implements java.io.Serializable, AbstractBO<UsdlogquId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsdlogquId id;
	private Date lquhoratf;
	private String lqutextaf;
	private String lqurespaf;
	private String lquparqaf;
	private String lqudescaf;

	public Usdlogqu() {
	}

	public Usdlogqu(UsdlogquId id, Date lquhoratf, String lqutextaf,
			String lqurespaf, String lquparqaf, String lqudescaf) {
		this.id = id;
		this.lquhoratf = lquhoratf;
		this.lqutextaf = lqutextaf;
		this.lqurespaf = lqurespaf;
		this.lquparqaf = lquparqaf;
		this.lqudescaf = lqudescaf;
	}

	public UsdlogquId getId() {
		return this.id;
	}

	public void setId(UsdlogquId id) {
		this.id = id;
	}

	public Date getLquhoratf() {
		return this.lquhoratf;
	}

	public void setLquhoratf(Date lquhoratf) {
		this.lquhoratf = lquhoratf;
	}

	public String getLqutextaf() {
		return this.lqutextaf;
	}

	public void setLqutextaf(String lqutextaf) {
		this.lqutextaf = lqutextaf;
	}

	public String getLqurespaf() {
		return this.lqurespaf;
	}

	public void setLqurespaf(String lqurespaf) {
		this.lqurespaf = lqurespaf;
	}

	/**
	 * @return the lquparqaf
	 */
	public String getLquparqaf() {
		return lquparqaf;
	}

	/**
	 * @param lquparqaf
	 *            the lquparqaf to set
	 */
	public void setLquparqaf(String lquparqaf) {
		this.lquparqaf = lquparqaf;
	}

	@Override
	public UsdlogquId getPrimaryKey() {
		return id;
	}

	@Override
	public void prepareObject() {

	}

	@Override
	public void prepareToUpdate() {

	}

	/**
	 * @return the lqudescaf
	 */
	public String getLqudescaf() {
		return lqudescaf;
	}

	/**
	 * @param lqudescaf
	 *            the lqudescaf to set
	 */
	public void setLqudescaf(String lqudescaf) {
		this.lqudescaf = lqudescaf;
	}

}
