package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:40:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsdlogquId generated by hbm2java
 */
public class UsdlogquId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String usuemaiak;
	private Date lqufechfk;
	private int lqunsecnk;

	public UsdlogquId() {
	}

	public UsdlogquId(String usuemaiak, Date lqufechfk, int lqunsecnk) {
		this.usuemaiak = usuemaiak;
		this.lqufechfk = lqufechfk;
		this.lqunsecnk = lqunsecnk;
	}

	public String getUsuemaiak() {
		return this.usuemaiak;
	}

	public void setUsuemaiak(String usuemaiak) {
		this.usuemaiak = usuemaiak;
	}

	public Date getLqufechfk() {
		return this.lqufechfk;
	}

	public void setLqufechfk(Date lqufechfk) {
		this.lqufechfk = lqufechfk;
	}

	public int getLqunsecnk() {
		return this.lqunsecnk;
	}

	public void setLqunsecnk(int lqunsecnk) {
		this.lqunsecnk = lqunsecnk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsdlogquId))
			return false;
		UsdlogquId castOther = (UsdlogquId) other;

		return ((this.getUsuemaiak() == castOther.getUsuemaiak()) || (this
				.getUsuemaiak() != null && castOther.getUsuemaiak() != null && this
				.getUsuemaiak().equals(castOther.getUsuemaiak())))
				&& ((this.getLqufechfk() == castOther.getLqufechfk()) || (this
						.getLqufechfk() != null
						&& castOther.getLqufechfk() != null && this
						.getLqufechfk().equals(castOther.getLqufechfk())))
				&& (this.getLqunsecnk() == castOther.getLqunsecnk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsuemaiak() == null ? 0 : this.getUsuemaiak().hashCode());
		result = 37 * result
				+ (getLqufechfk() == null ? 0 : this.getLqufechfk().hashCode());
		result = 37 * result + this.getLqunsecnk();
		return result;
	}

}
