package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:40:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import edu.upm.spbw.utils.Constants;

/**
 * Usdlogin generated by hbm2java
 */
public class Usdlogin implements java.io.Serializable, AbstractBO<UsdloginId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsdloginId id;
	private Date liuhoratf;
	private String liudiriaf;
	private String liuiexisf;
	/* Booleano */
	private boolean bliuiexisf;

	public Usdlogin() {
	}

	public Usdlogin(UsdloginId id, Date liuhoratf, String liudiriaf,
			String liuiexisf) {
		this.id = id;
		this.liuhoratf = liuhoratf;
		this.liudiriaf = liudiriaf;
		this.liuiexisf = liuiexisf;
	}

	public UsdloginId getId() {
		return this.id;
	}

	public void setId(UsdloginId id) {
		this.id = id;
	}

	public Date getLiuhoratf() {
		return this.liuhoratf;
	}

	public void setLiuhoratf(Date liuhoratf) {
		this.liuhoratf = liuhoratf;
	}

	public String getLiudiriaf() {
		return this.liudiriaf;
	}

	public void setLiudiriaf(String liudiriaf) {
		this.liudiriaf = liudiriaf;
	}

	public String getLiuiexisf() {
		return this.liuiexisf;
	}

	public void setLiuiexisf(String liuiexisf) {
		this.liuiexisf = liuiexisf;
	}

	@Override
	public UsdloginId getPrimaryKey() {
		return id;
	}

	@Override
	public void prepareObject() {
		// Booleano
		this.bliuiexisf = Constants.ONE.equals(this.liuiexisf);
	}

	@Override
	public void prepareToUpdate() {

	}

	/**
	 * @return the bliuiexisf
	 */
	public boolean isBliuiexisf() {
		return bliuiexisf;
	}

	/**
	 * @param bliuiexisf
	 *            the bliuiexisf to set
	 */
	public void setBliuiexisf(boolean bliuiexisf) {
		this.bliuiexisf = bliuiexisf;
	}

}
