package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:40:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsdloginId generated by hbm2java
 */
public class UsdloginId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String usuemaiak;
	private Date liufechfk;
	private int liunsecnk;

	public UsdloginId() {
	}

	public UsdloginId(String usuemaiak, Date liufechfk, int liunsecnk) {
		this.usuemaiak = usuemaiak;
		this.liufechfk = liufechfk;
		this.liunsecnk = liunsecnk;
	}

	public String getUsuemaiak() {
		return this.usuemaiak;
	}

	public void setUsuemaiak(String usuemaiak) {
		this.usuemaiak = usuemaiak;
	}

	public Date getLiufechfk() {
		return this.liufechfk;
	}

	public void setLiufechfk(Date liufechfk) {
		this.liufechfk = liufechfk;
	}

	public int getLiunsecnk() {
		return this.liunsecnk;
	}

	public void setLiunsecnk(int liunsecnk) {
		this.liunsecnk = liunsecnk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsdloginId))
			return false;
		UsdloginId castOther = (UsdloginId) other;

		return ((this.getUsuemaiak() == castOther.getUsuemaiak()) || (this
				.getUsuemaiak() != null && castOther.getUsuemaiak() != null && this
				.getUsuemaiak().equals(castOther.getUsuemaiak())))
				&& ((this.getLiufechfk() == castOther.getLiufechfk()) || (this
						.getLiufechfk() != null
						&& castOther.getLiufechfk() != null && this
						.getLiufechfk().equals(castOther.getLiufechfk())))
				&& (this.getLiunsecnk() == castOther.getLiunsecnk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsuemaiak() == null ? 0 : this.getUsuemaiak().hashCode());
		result = 37 * result
				+ (getLiufechfk() == null ? 0 : this.getLiufechfk().hashCode());
		result = 37 * result + this.getLiunsecnk();
		return result;
	}

}
