package edu.upm.spbw.persistence.bo;

// Generated 28-feb-2016 11:50:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang.exception.ExceptionUtils;

import edu.upm.spbw.persistence.dao.ICspperfuDAO;
import edu.upm.spbw.utils.ApplicationMessages;
import edu.upm.spbw.utils.Constants;
import edu.upm.spbw.utils.LogLogger;
import edu.upm.spbw.utils.SpringAppContext;

/**
 * Usmusuar generated by hbm2java
 */
public class Usmusuar implements java.io.Serializable, AbstractBO<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String usuemaiak;
	private String usunusuaf;
	private String usupassaf;
	private String pfucpfuak;
	private String usuestavf;
	private int usuilognf;
	private long usutblonf;
	private String usupascsf;
	private Date usufulcff;
	// Descripcion perfil
	private String pfudpduaf;
	/* booleanos */
	private boolean busupascsf;
	// Descripcion estado
	private String usuestaff;
	// Tiempo de bloqueo en String
	private Date usutbloff;

	public Usmusuar() {
	}

	public Usmusuar(String usuemaiak, String usunusuaf, String usupassaf,
			String pfucpfuak, String usuestavf, int usuilognf, long usutblonf,
			String usupascsf, Date usufulcff) {
		this.usuemaiak = usuemaiak;
		this.usunusuaf = usunusuaf;
		this.usupassaf = usupassaf;
		this.pfucpfuak = pfucpfuak;
		this.usuestavf = usuestavf;
		this.usuilognf = usuilognf;
		this.usutblonf = usutblonf;
		this.usupascsf = usupascsf;
		this.usufulcff = usufulcff;
	}

	public String getUsuemaiak() {
		return this.usuemaiak;
	}

	public void setUsuemaiak(String usuemaiak) {
		this.usuemaiak = usuemaiak;
	}

	public String getUsunusuaf() {
		return this.usunusuaf;
	}

	public void setUsunusuaf(String usunusuaf) {
		this.usunusuaf = usunusuaf;
	}

	public String getUsupassaf() {
		return this.usupassaf;
	}

	public void setUsupassaf(String usupassaf) {
		this.usupassaf = usupassaf;
	}

	public String getPfucpfuak() {
		return this.pfucpfuak;
	}

	public void setPfucpfuak(String pfucpfuak) {
		this.pfucpfuak = pfucpfuak;
	}

	public String getUsuestavf() {
		return this.usuestavf;
	}

	public void setUsuestavf(String usuestavf) {
		this.usuestavf = usuestavf;
	}

	public int getUsuilognf() {
		return this.usuilognf;
	}

	public void setUsuilognf(int usuilognf) {
		this.usuilognf = usuilognf;
	}

	public long getUsutblonf() {
		return this.usutblonf;
	}

	public void setUsutblonf(long usutblonf) {
		this.usutblonf = usutblonf;
	}

	public String getUsupascsf() {
		return this.usupascsf;
	}

	public void setUsupascsf(String usupascsf) {
		this.usupascsf = usupascsf;
	}

	public Date getUsufulcff() {
		return this.usufulcff;
	}

	public void setUsufulcff(Date usufulcff) {
		this.usufulcff = usufulcff;
	}

	@Override
	public String getPrimaryKey() {
		return usuemaiak;
	}

	/**
	 * @return the pfudpduaf
	 */
	public String getPfudpduaf() {
		return pfudpduaf;
	}

	/**
	 * @param pfudpduaf
	 *            the pfudpduaf to set
	 */
	public void setPfudpduaf(String pfudpduaf) {
		this.pfudpduaf = pfudpduaf;
	}

	/**
	 * @return the busupascsf
	 */
	public boolean isBusupascsf() {
		return busupascsf;
	}

	/**
	 * @param busupascsf
	 *            the busupascsf to set
	 */
	public void setBusupascsf(boolean busupascsf) {
		this.busupascsf = busupascsf;
	}

	@Override
	public void prepareObject() {
		// Campos
		if (usuemaiak == null)
			usuemaiak = Constants.BLANKS;
		else
			usuemaiak = usuemaiak.trim();
		if (usunusuaf == null)
			usunusuaf = Constants.BLANKS;
		else
			usunusuaf = usunusuaf.trim();
		if (usupassaf == null)
			usupassaf = Constants.BLANKS;
		else
			usupassaf = usupassaf.trim();
		if (pfucpfuak == null)
			pfucpfuak = Constants.BLANKS;
		else
			pfucpfuak = pfucpfuak.trim();
		if (usuestavf == null)
			usuestavf = Constants.ONE;
		else
			usuestavf = usuestavf.trim();
		if (usupascsf == null)
			usupascsf = Constants.ZERO;
		else
			usupascsf = usupascsf.trim();
		// Booleano
		this.busupascsf = Constants.ONE.equals(this.usupascsf);
		// Descripcion estado
		this.usuestaff = ApplicationMessages.getMessage("usmusuar_usuestavf_"
				+ this.usuestavf);
		// Tiempo de bloqueo
		if (this.usutblonf != 0) {
			this.usutbloff = new Date(this.usutblonf);
		} else {
			this.usutbloff = Constants.DEFAULT_DATE;
		}
		// Descripcion perfil si lo hay
		if (!Constants.BLANKS.equals(this.pfucpfuak)) {
			try {
				// Dao para leer CSPPERFU
				ICspperfuDAO cspperfuDao = SpringAppContext.getAppContext()
						.getBean(ICspperfuDAO.class);
				// Obtiene perfil
				Cspperfu perfu = cspperfuDao.findById(this.pfucpfuak);
				// Asigna descripcion
				this.pfudpduaf = perfu.getPfudpfuaf();
			} catch (Exception e) {/* Error obteniendo perfil */
				LogLogger.getInstance(this.getClass()).logger(
						ExceptionUtils.getFullStackTrace(e), LogLogger.ERROR);
			}
		}
	}

	@Override
	public void prepareToUpdate() {
		this.usupascsf = this.busupascsf ? Constants.ONE : Constants.ZERO;
	}

	/**
	 * @return the usuestaff
	 */
	public String getUsuestaff() {
		return usuestaff;
	}

	/**
	 * @param usuestaff
	 *            the usuestaff to set
	 */
	public void setUsuestaff(String usuestaff) {
		this.usuestaff = usuestaff;
	}

	/**
	 * @return the usutbloff
	 */
	public Date getUsutbloff() {
		return usutbloff;
	}

	/**
	 * @param usutbloff
	 *            the usutbloff to set
	 */
	public void setUsutbloff(Date usutbloff) {
		this.usutbloff = usutbloff;
	}

}
